// <auto-generated />
namespace SDE.MediaManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Podcast : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Podcast));
        
        string IMigrationMetadata.Id
        {
            get { return "201707261730442_Podcast"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
